### ISSUE TITLE
IPFS CID versioning not defined, may lead to errors 

### ISSUE THREAD

**Issue by sambacha** [dapphub/dpack#37]
We want to ensure that the CID is v1  and not v0. 

This is desired as CID v0s appear to be incompatible with IPFS subdomains, among other issues.

Currently there is no explicit version used for CID that I could find. 

> [reference, see docs.ipfs.io/concepts/content-addressing/#identifier-formats ](https://docs.ipfs.io/concepts/content-addressing/#identifier-formats )

**Comment by nmushegian** [comment]
latest will now warn if it sees v0 cid that it will later be an error. will emit v1 CIDs only
